# Generated by Django 5.1.7 on 2025-03-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_comment_likes_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='profile_pics/default-avatar.png', upload_to='profile_pics/'),
        ),
    ]
