# Generated by Django 5.1.7 on 2025-03-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='thread_image',
        ),
        migrations.AddField(
            model_name='thread',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
